# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='事件标题')),
                ('time', models.TimeField(verbose_name='事件时间段')),
                ('date', models.DateField(verbose_name='事件日期')),
                ('addr', models.CharField(max_length=100, verbose_name='事件发生地点')),
                ('desc', models.CharField(max_length=255, verbose_name='事件描述')),
            ],
            options={
                'db_table': 'SchoolEvent',
            },
        ),
    ]
