# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_views', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolevents',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='event_pic'),
        ),
    ]
