# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_views', '0002_schoolevents_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学员名字')),
                ('lesson', models.CharField(max_length=20, verbose_name='所学专业')),
                ('words', models.CharField(max_length=255, verbose_name='学员感言')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='client_pic')),
            ],
            options={
                'db_table': 'ClientSay',
            },
        ),
    ]
