# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='学生姓名')),
                ('birth', models.DateField(verbose_name='学生生日')),
                ('gender', models.CharField(max_length=2, verbose_name='学生性别')),
                ('email', models.EmailField(max_length=254, verbose_name='学生邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='学生电话')),
                ('course', models.CharField(max_length=50, verbose_name='选择课程')),
                ('course_time', models.CharField(max_length=50, verbose_name='课程时间')),
                ('addr', models.CharField(blank=True, max_length=255, verbose_name='学生地址')),
                ('line', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='')),
                ('zip_code', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'AdmissionInfo',
            },
        ),
    ]
